### ISSUE TITLE
Manual data entry

### ISSUE THREAD

**Issue by erichkleung** [Team4159/ScoutingBackend#2]
In case QR code scanning fails for whatever reason, can we come up with a way to quickly enter in the info from the individual apps? 

i.e. for team 2005, match 5, 1 gear in auto, 2 gears in tele-op
which we might cut down to `2005,5,1,2`
which maybe we can serialize to some format that can contain all of that information with less characters? Just food for thought

**Comment by brandonlou** [comment]
Manual entry 👍 and we can decide on a format for the csv
